"""initial schema

Revision ID: 4a72fcd92970
Revises: 
Create Date: 2026-09-20 07:24:14.708925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a72fcd92970'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=128), nullable=True),
    sa.Column('camera_type', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_protocol', sa.Enum('simulator', 'file', 'rtsp', 'onvif', name='sourceprotocol'), nullable=False),
    sa.Column('stream_ref_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', name='camerastatus'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_tier', sa.Enum('hot', 'warm', 'cold', name='storagetier'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarded_via', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cameras_department', 'cameras', ['department'], unique=False)
    op.create_index('ix_cameras_status', 'cameras', ['status'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('stolen_vehicle', 'blacklisted_vehicle', 'wanted_person', 'missing_person', 'other', name='watchlistcategory'), nullable=False),
    sa.Column('identifier_type', sa.Enum('plate', 'face_id', 'name', name='identifiertype'), nullable=False),
    sa.Column('identifier_value', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_identifier_value'), 'watchlist_entries', ['identifier_value'], unique=False)
    op.create_index('ix_watchlist_identifier', 'watchlist_entries', ['identifier_type', 'identifier_value'], unique=False)
    op.create_table('detection_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('anpr', 'vehicle_detection', 'person_detection', 'object_detection', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('person_ref', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_dedup_hash'), 'detection_events', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_detection_events_timestamp'), 'detection_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detection_events_vehicle_number'), 'detection_events', ['vehicle_number'], unique=False)
    op.create_index('ix_events_camera_time', 'detection_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index('ix_events_vehicle_time', 'detection_events', ['vehicle_number', 'timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=True),
    sa.Column('matched_identifier', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.Enum('stolen_vehicle', 'blacklisted_vehicle', 'wanted_person', 'missing_person', 'other', name='watchlistcategory'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'resolved', name='alertstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_time', 'alerts', ['status', 'timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index('ix_alerts_status_time', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_events_vehicle_time', table_name='detection_events')
    op.drop_index('ix_events_camera_time', table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_vehicle_number'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_timestamp'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_dedup_hash'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index('ix_watchlist_identifier', table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_identifier_value'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index('ix_cameras_status', table_name='cameras')
    op.drop_index('ix_cameras_department', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
